### ISSUE TITLE
unable to use `EthMevProdiferExt` when using `alloy-mev`

### ISSUE THREAD

**Issue by 0xrusowsky** [leruaa/alloy-mev#7]
hey @leruaa, first of all thanks for building this crate! I'm sure it will be super helpful 🙂

I am trying to use it, but i seem to be unable to properly bring the `EthMevProviderExt` trait into scope. Despite following your docs and tests, the compiler is unable to link it with `FillProvider`, therefore giving me a warning for having an unused import (`EthMevProviderExt`) as well as an error because `.endpoints_builder()` is not found in `FillProvider<...>`.

Could you please let me know if i'm doing something wrong? I've set up a [dummy repo](https://github.com/0xrusowsky/test-alloy-mev/tree/main) where i try to replica one of your tests, so that you could see the imports and dependencies.

PS: I also tried forking your repo and running the tests and, as expected, they work.

Thanks in advance,

**Comment by leruaa** [comment]
The published alloy-mev v0.2.0 on crates.io was based on alloy 0.1.4. As you depends on alloy 0.2.0, the types aren't the same.

I've just published alloy-mev v0.2.1 that fix this issue.

Sorry about that.

**Comment by 0xrusowsky** [comment]
oh, i completely missed that! since they did the upgrade to v0.2 not too long ago i assumed that your crate was aligned with theirs.

thanks for the quick fix 🤝
